---
title: "Homework5"
output:
  pdf_document: default
  html_document:
    df_print: paged
date: "2025-04-09"
---

```{r}
pacman::p_load(tidyverse)
wdi <- read.csv('./data/wdi.csv')
```


```{r}
wdi_region <- wdi %>%
  mutate(Region =case_when(country == "Argentina" ~ "South America",
                           country == "Bolivia" ~ "South America",
                           country == "Brazil" ~ "South America",
                           country == "Chile" ~ "South America",
                           country == "Colombia" ~ "South America",
                           country == "Ecuador" ~ "South America",
                           country == "Guyana" ~ "South America",
                           country == "Paraguay" ~ "South America",
                           country == "Peru" ~ "South America",
                           country == "Suriname" ~ "South America",
                           country == "Uruguay" ~ "South America",
                           country == "Venezuela, RB" ~ "South America",
                           country == "Australia" ~ "Oceania",
                           country == "Cook Islands" ~ "Oceania",
                           country == "Micronesia, Fed. Sts." ~ "Oceania",
                           country == "Fiji" ~ "Oceania",
                           country == "Kiribati" ~ "Oceania",
                           country == "Marshall Islands" ~ "Oceania",
                           country == "Nauru" ~ "Oceania",
                           country == "New Zealand" ~ "Oceania",
                           country == "Palau" ~ "Oceania",
                           country == "Papua New Guinea" ~ "Oceania",
                           country == "Samoa" ~ "Oceania",
                           country == "Solomon Islands" ~ "Oceania",
                           country == "Tonga" ~ "Oceania",
                           country == "Tuvalu" ~ "Oceania",
                           country == "Vanuatu" ~ "Oceania",
                            TRUE ~ "Rest of the world"))
ggplot(data = wdi_region, mapping = aes(y=measles_immunisation_rate, x = life_expectancy,color = Region))+
  geom_point(alpha = 0.4)+ 
  labs(title = "Measles Immunization Rate by Life Expectancy",x = "Life Expectancy", y = "Measles Immunization Rate")
```



```{r}
wdi_region_grouped <- wdi_region %>% 
  group_by(Region) %>% 
  summarize(AvgGDP = mean(gdp_per_capita, na.rm=TRUE),
            AvgInflation = mean(inflation_rate, na.rm=TRUE),
            AvgLife = mean(life_expectancy, na.rm=TRUE),
            AvgGDPGrowth = mean(gdp_growth_rate, na.rm=TRUE))

ggplot(wdi_region_grouped, mapping = aes(x=Region, y = AvgGDP, fill = Region)) + 
  geom_col() +
  labs(title = "Average GDP by Region", x = "Region", y = "Average GDP")
```

|                  | GDP per Capita | GDP Growth Rate | Inflation | Life Expectancy | 
|:---------|:--------:|:--------:|:--------:|---------:|
|       Oceania      |    12737.43    |     2.43594     |  7.543184 |     70.61023    |
|  Rest of the World |    21567.47    |     4.22497     | 12.845402 |     72.51298    |
|    South America   |    10258.62    |     9.14499     | 12.207844 |     72.89433    |
